config/unicorn.rb

Report generation for large datasets is timing out in users browsers
resulting in a 502 response.
This initial change will allow the ruby process more time to generate
the report response. A change to the associated Apache proxy connection
will also be added in AAF Ansible.
This is a partial solution for #148.

Extend request timeout to 5 minutes

---

app/reports/subscriber_registrations_report.rb

Ensures that javascript engines in browsers can correctly display
date data, previously this resulted in NaN output in at least Firefox.
Closes #146.

Correct date format in JSON for sub reg reports

---

config/boot.rb

Missed this one in review, but hit it in my local environment while testing something unrelated.

Fix implicit Torba step during "rake assets:precompile"

---

app/reports/identity_provider_destination_services_report.rb
app/reports/identity_provider_utilization_report.rb
app/reports/reports_shared_methods.rb
app/reports/service_provider_source_identity_providers_report.rb
app/reports/service_provider_utilization_report.rb
db/migrate/20160613235908_add_indexes_for_utilization_reports.rb
db/schema.rb
db/seeds.rb
spec/support/utilization_reports.rb

A couple of issues were at play here which caused these reports to run far too slowly:
* Original implementation was loading every `DiscoveryServiceEvent` into an ActiveRecord object, which is _far_ too slow for the amount of data we have;
* The query to select relevant `DiscoveryServiceEvent` records was not hitting the correct index, leading to performance indistinguishable from a full table scan.
Switching to an aggregate query and fixing the index makes a dramatic difference.
cc @toomaj If you want to also look at what I've done here.

Fix run speed of utilization reports

---

app/models/subject.rb

Fixes #161.
When incoming subject has only one permission, then preloading
permissions causes `Bullet` to raise `unused` preload exception,
and if subject has more that one permission then Bullet raises
`SELECT N+1` exception when permissions are not preloaded.
My approach to fix this problem is to establish an extra
association between `subject` and related `permissions`
through `roles`, and invoke permissions directly on subject
to solve `unused preload` or `N+1 Query` issues.

Refactor #permissions to always be optimized query 

---

Gemfile.lock

When deployed in a clean environment, running `rake assets:precompile` would raise the following exception:
```
NoMethodError: undefined method `find_asset' for nil:NilClass
aaf-lipstick-48aeef08fe3f/lib/lipstick/images/email_banner.rb:90:in `logo'
aaf-lipstick-48aeef08fe3f/lib/lipstick/images/email_banner.rb:100:in `logo_w'
aaf-lipstick-48aeef08fe3f/lib/lipstick/images/email_banner.rb:157:in `total_w'
aaf-lipstick-48aeef08fe3f/lib/lipstick/images/email_banner.rb:125:in `margin_x'
aaf-lipstick-48aeef08fe3f/lib/lipstick/images/email_banner.rb:131:in `title_x'
aaf-lipstick-48aeef08fe3f/lib/lipstick/images/email_banner.rb:81:in `annotate_title'
aaf-lipstick-48aeef08fe3f/lib/lipstick/images/email_banner.rb:43:in `to_png'
aaf-lipstick-48aeef08fe3f/lib/lipstick/images/processor.rb:20:in …
```

Update Lipstick to fix asset precompilation bug

---

app/controllers/administrator_reports_controller.rb
app/controllers/subscriber_reports.rb
lib/steps.rb
spec/support/scaling_steps.rb

Ruby's subtraction of dates took into account the shorter February
month.  When you compare this result with `1.month` (ie. 30 days in
Rubyland) you get an incorrect comparison and a failing test.
This creates a small exception for February, removes duplicate code and
adds a February specific test in.

Fix time bug for the shorter February month

---

config/initializers/session_store.rb

Rails defaults to not marking cookies as secure.
Prevent cookie theft over plain http: mark cookies as secure
This will apply to the Ruby stack across the board - I may send another one for IdE, but you may wish to consider applying the same change to all other projects...
Cheers,
Vlad

Config: use secure session cookies

---

Gemfile
Gemfile.lock
config/reporting_service.yml.dist
lib/authentication/subject_receiver.rb
spec/features/administrator_reports_spec.rb
spec/features/automated_report_instances_spec.rb
spec/features/automated_reports_spec.rb
spec/features/compliance_reports_spec.rb
spec/features/federation_reports_spec.rb
spec/features/identity_provider_reports_spec.rb
spec/features/login_spec.rb
spec/features/service_provider_reports_spec.rb
spec/features/subscriber_reports_dashboard_spec.rb
spec/rails_helper.rb

Removes reliance on IdE and instead deploys a simple mapping of AEPST to Entitlement strings within the application config file.
Fixes #195.

Remove IdE integration

---

.gitignore
Gemfile
Gemfile.lock

In haml versions prior to version 5.0.0.beta.2, when using user input to
perform tasks on the server, characters like < > " ' must be escaped
properly. In this case, the ' character was missed. An attacker can
manipulate the input to introduce additional attributes, potentially
executing code.

CVE-2017-1002201

---

.gitignore
Gemfile
Gemfile.lock

Reverts ausaccessfed/reporting-service#198
This commit is breaking test federation reporting due to unnoticed bundler update being included.
```
TEST reporting@app5:~$ /opt/reporting/scripts/receive_events.sh
You must use Bundler 2 or greater with this lockfile.
```

Revert "CVE-2017-1002201"

---

app/jobs/concerns/query_federation_registry.rb
app/jobs/update_from_rapid_connect.rb

This was causing cron jobs to fail, with the error:
```
app/jobs/concerns/query_federation_registry.rb:18:in `fr_data': uninitialized constant Net::HTTP (NameError)
```

Require 'net/http' where it's needed

---

db/migrate/20200209214427_change_timestamp_type.rb
db/schema.rb

Fixes #210
In MySQL, TIMESTAMP is stored as unixt time integer - and even when storing a
UTC timestamp value into the field, MySQL treats it as a local timestamp in the
server timezone - and applies a conversion to UTC, converting back upon
retrieval.
Besides this being additional overhead, it also breaks when the UTC timestamp
stored falls on a period which does not exist in the local timezone (because of
DST change) - but is otherwise a perfectly valid UTC timestamp.
The DATETIME type does not have any of these downaides and is more suitable for
storing datetime values where the application knows what timezone they're in
(UTC in case of Reporting Service) and stops MySQL from making a (possibly
wrong) guess.
All rspec tests pass.

DB: change all t.timestamp fields to use t.datetime

---

config/initializers/session_store.rb

As per https://github.com/redis-store/redis-rails
the correct key name is `expiry_after`.
When using `expire_in`, it does correctly set the Redis key expiry date,
but is ignored when constructing the cookie.
When using `expire_after`, the expiry is correctly applied to both
the Redis key and the session cookie.

Config: use correct key for session expiry

---

app/jobs/receive_events_from_discovery_service.rb
spec/jobs/receive_events_from_discovery_service_spec.rb

Invalid imports from DS logs threw off reporting ingest. These events
are not important to us so we should simply drop them and carry on.
Specific case leading to this change was an entityID in excess of 255
char, we don't support registration of entityID that long to the request
was clearly junk from the wider internet.

Ignore invalid events from DS

---

app/views/service_provider_reports/source_identity_providers_report.html.slim

Fix report title to match what the report is (and so also match the filename it's in and the link that leads to it).

Fix typo in report title (SP Dest Services => Source IdP)

---

app/jobs/update_from_federation_registry.rb
spec/jobs/update_from_federation_registry_spec.rb

Otherwise, these objects would appear as deactivated to the reporting service.
This in particular applies to objects that were not approved in FR yet when synced into Reporting Service - they were seen as not functioning, and were created as deactivated ... and would otherwise never get (re)activated in Reporting Service, even when they become activate in FR.
@bradleybeddoes , I ran into this when wondering why I'm not seeing an SP in the list on the Reporting Service ... and found this issue, hiding SPs that were synced before they got approved.
Fix so far tested in our TEST environment, does exactly what it should.

Fix: fr-sync: functioning objects must have empty deactivation time

---

Gemfile.lock

For details on this issue, refer here: https://github.com/ausaccessfed/stockpile/issues/89
This is part of https://github.com/ausaccessfed/stockpile/issues/87

Revert `execJS` gem to `2.7.0`

---

Gemfile.lock

The following scripts are failing to run:
- receive_events.sh 
- update.sh
I checked aws log groups for the instance where it is running and the only log I could find was that <script> finished with exit code 1
I connected to the box and attempted to run the scripts manually to try and see the log output, however the following error appeared: 
```shell
TEST <redacted>@<redacted>:$ ./receive_events.sh
Your bundle only supports platforms ["x86_64-darwin-20"] but your local platform is x86_64-linux. Add the current platform to the lockfile with `bundle lock --add-platform x86_64-linux` and try again.
TEST <redacted>@<redacted>:$ ./update.sh
Your bundle only supports platforms ["x86_64-darwin-20"] but your local platform is x86_64-linux. Add the current platform to the lockfile with `bundle …
```

Add platform `x86_64-linux`

---

Gemfile.lock
config/initializers/session_store.rb
config/reporting_service_configuration.rb

Hi @phyzical ,
I've started looking at rolling out the NNWO changes for us: found two minor issues:
* cookies lost their `secure` flag in `session_store` change
* move from config file to env vars ended up hard-coding some settings.  Adding env vars for those that we override - preserving existing values as defaults if not set.  `TIME_ZONE` matches what e.g. validator-service already uses.
Please let me know if happy to merge like this or if any changes are required.
Cheers,
Vlad

Two minor fixes post NNWO: secure cookies and more env vars

---

app/jobs/receive_events_from_discovery_service.rb
config/application.rb
config/reporting_service_configuration.rb
spec/jobs/receive_events_from_discovery_service_spec.rb

Looks like when we moved to the inbuilt redis cache the default expiry is no longer being sent, fix up the name of the param to set default expiry

Fixing redis expiry

---

config/initializers/sentry.rb

Puma raises this error when a client makes a malformed HTTP request. It responds appropriately with 400 Bad Request. That's exactly what we want to happen! We don't need to be notified.
Reusing https://github.com/ausaccessfed/federationmanager/pull/2491

Have Sentry ignore Puma::HttpParserError

---

Dockerfile

node installation using scripts setup_XX.x has been deprecated. This uses the newly recommended nodistro package in rpm. similar to fix in https://github.com/ausaccessfed/federationmanager/issues/3014.

update node installation

---

Rakefile
package.json
yarn.lock

This was a big speedup when we used prettier to format Ruby, but now that we use syntax-tree it slows things down.

Remove parallel-prettier
